services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  Metabolism\WordpressBundle\ArgumentResolver\PostCollectionValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Metabolism\WordpressBundle\ArgumentResolver\PostValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Metabolism\WordpressBundle\ArgumentResolver\TermValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Metabolism\WordpressBundle\ArgumentResolver\UserValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  Metabolism\WordpressBundle\Twig\TwigGlobalSubscriber:
    tags:
      - { name: kernel.event_listener, event: kernel.request }

  Metabolism\WordpressBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Action/'
      - '../src/Entity/'
      - '../src/Factory/'
      - '../src/Helper/'
      - '../src/Loader/'
      - '../src/Traits/'
      - '../src/Routing/'
